// P4A task 6.1 — spike-level performance probe for the TypeScript candidate.
//
// Measures (3 iterations each, median + all samples recorded):
//   1. Lezer full parse of the ~1MB / ~10MB deterministic synthetic fixtures
//      (same bytes as the Rust harness reads — generated by
//      explore/gen-perf-fixtures.mjs, mulberry32 seed 42);
//   2. full parse through CodeMirror's incremental driver
//      (`ensureSyntaxTree(state, doc.length)`);
//   3. viewport-bounded incremental parse (`ensureSyntaxTree(state, 5000)`)
//      — the projection-relevant number: how long until the visible range
//      has a tree, vs parsing everything.
//
// This is a spike-grade wall-clock probe on one machine, NOT the frozen SLO
// benchmark of design/05 §6 (which requires cold/warm runs, p50/p95/p99 and
// per-platform judging). Numbers here only rank candidates.
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { EditorState } from '@codemirror/state';
import { markdown } from '@codemirror/lang-markdown';
import { GFM } from '@lezer/markdown';
import { ensurePerfFixtures } from './explore/gen-perf-fixtures.mjs';

const outDir = process.env.SPIKE_OUT ?? path.join(path.dirname(fileURLToPath(import.meta.url)), 'out');

const VIEWPORT_UTF16 = 5000; // ~ first 100 lines of the synthetic fixtures
const ITERATIONS = 3;

function median(xs) {
  const s = [...xs].sort((a, b) => a - b);
  return s[Math.floor(s.length / 2)];
}

/**
 * Block-varied deterministic document (heading/paragraph/list/fence pattern),
 * repeated to ~target UTF-16 units. The word-salad fixtures above are ONE
 * giant paragraph (no blank lines) — an earlier probe showed ensureSyntaxTree
 * then cannot stop before the paragraph ends (recorded as a granularity
 * finding). This variant measures viewport parse on a realistic structure.
 */
function blockVariedDoc(targetUtf16) {
  const blocks = [];
  let k = 0;
  let size = 0;
  while (size < targetUtf16) {
    k++;
    const chunk = [
      `## Heading ${k}`,
      '',
      `Paragraph ${k} with markdown fixture words 中文 😀 and plain text continues for a few lines.`,
      'Second line of the paragraph to make it multi-line soft-break content.',
      '',
      `- item alpha ${k}`,
      `- item beta ${k}`,
      '  - nested item',
      '',
      '```js',
      `const k${k} = ${k}; // fenced code block`,
      '```',
      '',
      '',
    ].join('\n');
    blocks.push(chunk);
    size += chunk.length + 1;
  }
  return blocks.join('\n');
}

describe('P4A 6.1 — Lezer performance probe', () => {
  it('times full parse vs viewport-bounded incremental parse', async () => {
    const manifest = await ensurePerfFixtures();
    const language = markdown({ extensions: [GFM] });
    const results = [];

    for (const fx of manifest) {
      const text = (await readFile(fx.file, 'utf8'));
      expect(text.length).toBe(fx.utf16Length);
      const isVaried = fx.file.includes('varied');

      // 1) raw Lezer parse via the language's parser
      const parser = language.language.parser;
      const directSamples = [];
      for (let i = 0; i < ITERATIONS; i++) {
        const t0 = performance.now();
        const tree = parser.parse(text);
        directSamples.push(performance.now() - t0);
        expect(tree.length).toBe(text.length);
      }

      // 2) full parse through the incremental driver (warm EditorState each time)
      const fullSamples = [];
      for (let i = 0; i < ITERATIONS; i++) {
        const state = EditorState.create({ doc: text, extensions: [language] });
        const t0 = performance.now();
        const tree = (await import('@codemirror/language')).ensureSyntaxTree(state, text.length, 1e9);
        fullSamples.push(performance.now() - t0);
        expect(tree.length).toBe(text.length);
      }

      // 3) viewport-bounded parse: tree ready for the first VIEWPORT_UTF16 units
      const viewportSamples = [];
      let viewportParsedTo = 0;
      for (let i = 0; i < ITERATIONS; i++) {
        const state = EditorState.create({ doc: text, extensions: [language] });
        const t0 = performance.now();
        const tree = (await import('@codemirror/language')).ensureSyntaxTree(state, VIEWPORT_UTF16, 1e9);
        viewportSamples.push(performance.now() - t0);
        viewportParsedTo = tree.length; // how far the partial parse actually reached
      }

      // 3b) same viewport probe on a block-varied document (~same size):
      // measures the realistic "tree ready for the visible range" cost.
      const varied = blockVariedDoc(fx.utf16Length);
      const variedSamples = [];
      let variedParsedTo = 0;
      for (let i = 0; i < ITERATIONS; i++) {
        const state = EditorState.create({ doc: varied, extensions: [language] });
        const t0 = performance.now();
        const tree = (await import('@codemirror/language')).ensureSyntaxTree(state, VIEWPORT_UTF16, 1e9);
        variedSamples.push(performance.now() - t0);
        variedParsedTo = tree.length;
      }

      results.push({
        fixture: path.basename(fx.file),
        kind: isVaried ? 'block-varied' : 'giant-paragraph',
        byteLength: fx.byteLength,
        sha256: fx.sha256,
        utf16Length: fx.utf16Length,
        directFullParseMs: { samples: directSamples, median: median(directSamples) },
        cmFullParseMs: { samples: fullSamples, median: median(fullSamples) },
        ...(isVaried
          ? {}
          : {
              cmViewportParseGiantParagraphMs: { samples: viewportSamples, median: median(viewportSamples), viewportUtf16: VIEWPORT_UTF16, parsedTo: viewportParsedTo, note: 'word-salad fixture is ONE paragraph (no blank lines) — parse cannot stop early' },
            }),
        cmViewportParseMs: { samples: variedSamples, median: median(variedSamples), viewportUtf16: VIEWPORT_UTF16, parsedTo: variedParsedTo, docUtf16: varied.length },
      });
    }

    const report = {
      spike: 'parser-candidate-performance',
      task: 'P4A 6.1 (Lezer performance probe)',
      generatedAt: new Date().toISOString(),
      note: 'spike-grade wall-clock probe on one machine; 3 iterations; not the frozen SLO benchmark (design/05 §6)',
      machine: { platform: process.platform, arch: process.arch, node: process.version },
      results,
    };
    await mkdir(outDir, { recursive: true });
    const file = path.join(outDir, 'perf-ts.json');
    await writeFile(file, JSON.stringify(report, null, 1) + '\n');
    console.log(`[spike] wrote ${file}`);

    for (const r of results) {
      expect(r.directFullParseMs.median).toBeGreaterThan(0);
      expect(r.cmViewportParseMs.parsedTo).toBeGreaterThan(0);
      expect(r.cmViewportParseMs.parsedTo).toBeLessThanOrEqual(Math.max(r.utf16Length, r.cmViewportParseMs.docUtf16));
    }
  });
});
